name: Build

on:
  push:
    branches:
      - trial
  workflow_dispatch:

jobs:
  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .
      - name: Install dependencies
        run: |
          sudo apt-get install -y python3 python3-pip

      - name: Build package
        run: |
          pip install --upgrade build
          python -m build
          tree .

      - name: Artifact creation
        run: |
          rm dist/my_package-0.0.0.tar.gz
          mv script.py dist/script.py
          tree .

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist/

  deploy:
    name: Deploy Job
    needs: with-checkout-job
    runs-on: 'ubuntu-latest'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Run script.py
        run: |
          ls -R
          pip install *.whl
          python script.py


